openapi: 3.0.1
info:
  title: E-commerce API
  version: 1.0.0

servers:
  - url: http://localhost:3001
    description: Localhost server

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        price:
          type: number
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Created
  /products/{productId}:
    get:
      summary: Get a product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: number
          description: ID of the product to retrieve
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
